### ISSUE TITLE
Boundary detection

### ISSUE THREAD

**Issue by reynoldscem** [aayushbansal/PixelNet#3]
Hello. Thank you for providing your code.

You seem not to include prototxt files or caffemodels for the boundary detection tasks. Why is this?

**Comment by aayushbansal** [comment]
Thanks for your interest in PixelNet. A few models along with boundary detection are remaining. I will try to put them up by this weekend.

**Comment by reynoldscem** [comment]
Thank you.

**Comment by ryx19th** [comment]
It seems that the edge detection model hasn't been uploaded yet, has it?

Or maybe I should use the model in `models/analysis/lin_bn/semantic_seg` because it is said in the paper that

> We use the same baseline network that was defined for semantic segmentation, only making use of pretrained *conv* layers.

, should I?

Thank you.

**Comment by aayushbansal** [comment]
Uploaded.
