### ISSUE TITLE
Pixel Location for multi-class problem

### ISSUE THREAD

**Issue by SavanGowda** [aayushbansal/PixelNet#4]
Hi @aayushbansal 

Thanks for providing the code for PixelNet.  I have a small issue regarding the pixel selection in case of Multi-class problems. In Multi-class problems do we need to take the class-specific sparse set of pixel location or is it the sparse set of pixel locations anywhere in the Image. In case of 224x224 image what number of sparse pixel locations might be a good choice for multi-class segmentation.
As I new to this I am a bit confused. Looking forward for any help.

Thanks & Regards
Savan

**Comment by aayushbansal** [comment]
Nope, you do not need to take class-specific sparse set. 

2000 random pixels are good enough.
