### ISSUE TITLE
The specified key is not present in this container.

### ISSUE THREAD

**Issue by alliecc** [aayushbansal/PixelNet#5]
Hello aayushbansal,

Thanks for sharing your code! 

I installed the caffe version in tool folder and then try to run demo_code.m.
But I got the following error. Do you have any idea about this?

----------------------------------------------------------------------
Image : ./experiments/demo/img_000001.jpg
Error using containers.Map/subsref
The specified key is not present in this container.

Error in caffe.Net/blobs (line 77)
      blob = self.blob_vec(self.name2blob_index(blob_name));

Error in demo_code (line 53)
        net.blobs('data0').reshape([crop_height+200, crop_width+200, 3, 1]);

Error in run (line 96)
evalin('caller', [script ';']);

 ----------------------------------------------------------------------

**Comment by aayushbansal** [comment]
Thanks for the pointer! I have made the edit. Now it should work.

**Comment by alliecc** [comment]
Thanks a lot!
