### ISSUE TITLE
test code

### ISSUE THREAD

**Issue by liuhuaer** [aayushbansal/PixelNet#6]
can you share your testing code of semantic segmentation

**Comment by liuhuaer** [comment]
I have train my model,can you help me for testing?

**Comment by aayushbansal** [comment]
I am sorry I have been busy, and not being able to respond. I will positively put the remaining models and test codes by this weekend. Very sorry for the delay, and thank you very much for your interest in PixelNet.

**Comment by liuhuaer** [comment]
thank you very much!!!

**Comment by eliethesaiyan** [comment]
@aayushbansal ,any update about the testing code?thank you

**Comment by aayushbansal** [comment]
Updated.

**Comment by eliethesaiyan** [comment]
@aayushbansal ,is the colormap.mat file specified in demo_seg? the same as the one used Voclabelcolormap.m,i can`t seem to find it in experiments/demo/demo_seg/?

**Comment by deartonym** [comment]
@aayushbansal, it seems that we don't have the folder './experiments/demo/demo/' that should contain necessary files for the demos. Is there anything that I get wrong?

Thanks.

**Comment by aayushbansal** [comment]
@eliethesaiyan @deartonym  - you may want to download the data mentioned in README in that respective folder.

**Comment by eliethesaiyan** [comment]
@aayushbansal ,i think i did everything the instruction requires,the colormap.mat file used in testing segmentation is not present.,the only file that is available is in experiments/train/data/PASCAL/VOC2012/VOCdevkit/VOCcode/VOClabelcolormap.m,is it the same?
